/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/produtos/cadastrar-produto` | `/produtos/cadastrar-produto`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/produtos/productsform` | `/produtos/productsform`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/relatorios/relatorios` | `/relatorios/relatorios`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/vendas/vendas` | `/vendas/vendas`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(public)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/produtos/cadastrar-produto` | `/produtos/cadastrar-produto`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/produtos/productsform` | `/produtos/productsform`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/relatorios/relatorios` | `/relatorios/relatorios`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/vendas/vendas` | `/vendas/vendas`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(public)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/produtos/cadastrar-produto${`?${string}` | `#${string}` | ''}` | `/produtos/cadastrar-produto${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/produtos/productsform${`?${string}` | `#${string}` | ''}` | `/produtos/productsform${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/relatorios/relatorios${`?${string}` | `#${string}` | ''}` | `/relatorios/relatorios${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/vendas/vendas${`?${string}` | `#${string}` | ''}` | `/vendas/vendas${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(public)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/produtos/cadastrar-produto` | `/produtos/cadastrar-produto`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/produtos/productsform` | `/produtos/productsform`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/relatorios/relatorios` | `/relatorios/relatorios`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/vendas/vendas` | `/vendas/vendas`; params?: Router.UnknownInputParams; };
    }
  }
}
